services:
  yt-tool-webui:
    image: yt-tool-webui
    container_name: yt-tool-webui
    build: .
    ports:
      - "8047:8047"
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./outputs:/app/outputs
    environment:
      - TZ=America/Mexico_City
      - YTDL_DATA_PATH=/app/data
      - YTDL_DOWNLOAD_PATH=/app/downloads
      - YTDL_OUTPUT_PATH=/app/outputs
    depends_on:
      - pot-provider
    restart: unless-stopped

  pot-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: pot-provider
    restart: unless-stopped
