<template>
  <div>
    <div class="section-header">
      <h1 class="section-title">Settings</h1>
      <span class="section-sub">server-side settings</span>
    </div>

    <div class="panel">
      <div class="panel-label">Paths</div>

      <div class="field">
        <label class="field-label">Data path <span style="color:var(--muted);font-weight:400">(settings, jobs, logs)</span></label>
        <input type="text" v-model="cfg.data_path" placeholder="/app/data" />
      </div>

      <div class="field">
        <label class="field-label">Download path <span style="color:var(--muted);font-weight:400">(temporary files)</span></label>
        <input type="text" v-model="cfg.download_path" placeholder="/app/downloads" />
      </div>

      <div class="field">
        <label class="field-label">Output path <span style="color:var(--muted);font-weight:400">(finished files)</span></label>
        <input type="text" v-model="cfg.output_path" placeholder="/app/outputs" />
      </div>

      <div class="field">
        <label class="field-label">Cookies.txt path <span style="color:var(--muted);font-weight:400">(optional)</span></label>
        <input type="text" v-model="cfg.cookies_path" placeholder="/app/cookies.txt" />
      </div>
    </div>

    <div class="panel">
      <div class="panel-label">Connection</div>

      <div class="field" style="margin-top:14px">
        <label
          :class="['toggle-row', { checked: cfg.enable_ytdlp_potoken }]"
          @click="cfg.enable_ytdlp_potoken = !cfg.enable_ytdlp_potoken"
        >
          <div class="toggle-box">
            <svg class="toggle-check" viewBox="0 0 8 8" fill="none">
              <path d="M1 4l2 2 4-4" stroke="#0a0a0b" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </div>
          Enable PO Token for standard downloads (yt-dlp)
        </label>
      </div>

      <div class="field" v-if="cfg.enable_ytdlp_potoken">
        <label class="field-label">PO Token <span style="color:var(--muted);font-weight:400">(Auto-generated by default. Paste here ONLY to override)</span></label>
        <input type="text" v-model="cfg.potoken" placeholder="Paste PO token here" autocomplete="off" />
      </div>

      <div class="field" style="margin-top:14px">
        <label
          :class="['toggle-row', { checked: cfg.auto_proxy_enabled }]"
          @click="cfg.auto_proxy_enabled = !cfg.auto_proxy_enabled"
        >
          <div class="toggle-box">
            <svg class="toggle-check" viewBox="0 0 8 8" fill="none">
              <path d="M1 4l2 2 4-4" stroke="#0a0a0b" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </div>
          Enable Auto Proxy Pool (Background managed)
        </label>
        <div style="font-size:10px; color:var(--muted); margin-top:4px; padding-left:24px;">
          Automatically find and rotate healthy proxies when the system is idle.
        </div>
      </div>

      <div class="field" style="margin-top:14px" v-if="!cfg.auto_proxy_enabled">
        <label
          :class="['toggle-row', { checked: cfg.proxy_enabled }]"
          @click="cfg.proxy_enabled = !cfg.proxy_enabled"
        >
          <div class="toggle-box">
            <svg class="toggle-check" viewBox="0 0 8 8" fill="none">
              <path d="M1 4l2 2 4-4" stroke="#0a0a0b" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </div>
          Enable Manual Proxy
        </label>
      </div>

      <template v-if="cfg.proxy_enabled && !cfg.auto_proxy_enabled">
        <div class="field" style="margin-top:14px">
          <label class="field-label">Type</label>
          <select v-model="cfg.proxy_type">
            <option value="http">HTTP</option>
            <option value="socks4">SOCKS4</option>
            <option value="socks5">SOCKS5</option>
          </select>
        </div>

        <div class="field-group" style="grid-template-columns: 1fr 100px;">
          <div class="field">
            <label class="field-label">Host</label>
            <input type="text" v-model="cfg.proxy_host" placeholder="e.g. 192.168.1.1 or proxy.example.com" />
          </div>
          <div class="field">
            <label class="field-label">Port</label>
            <input type="number" v-model="cfg.proxy_port" placeholder="e.g. 1080" />
          </div>
        </div>

        <div class="field" style="margin-top:14px">
          <label
            :class="['toggle-row', { checked: cfg.proxy_auth_enabled }]"
            @click="cfg.proxy_auth_enabled = !cfg.proxy_auth_enabled"
          >
            <div class="toggle-box">
              <svg class="toggle-check" viewBox="0 0 8 8" fill="none">
                <path d="M1 4l2 2 4-4" stroke="#0a0a0b" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            Requires Authentication
          </label>
        </div>

        <template v-if="cfg.proxy_auth_enabled">
          <div class="field-group">
            <div class="field">
              <label class="field-label">Username</label>
              <input type="text" v-model="cfg.proxy_username" autocomplete="username" />
            </div>
            <div class="field">
              <label class="field-label">Password</label>
              <input type="password" v-model="cfg.proxy_password" autocomplete="current-password" />
            </div>
          </div>
        </template>
      </template>
    </div>

    <div class="panel">
      <div class="panel-label">Advanced</div>
      <div class="btn-row">
        <button class="btn btn-ghost" @click="showAdvanced = !showAdvanced">
          <svg width="13" height="13" viewBox="0 0 13 13" fill="none" style="margin-right:4px">
            <path d="M2 4l4.5 4.5L11 4" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round" :style="{ transform: showAdvanced ? 'rotate(180deg)' : '', transformOrigin: 'center' }"/>
          </svg>
          {{ showAdvanced ? 'Hide Advanced Settings' : 'Show Advanced Settings' }}
        </button>
      </div>

      <div v-if="showAdvanced" style="margin-top:16px">
        <div class="msg msg-error" style="margin-bottom:16px">
          <div style="margin-bottom:4px"><strong>Warning: Experimental</strong></div>
          Custom arguments may conflict with the tool's internal flags and break functionality. Use with caution.
        </div>

        <div class="field">
          <label class="field-label">yt-dlp additional args</label>
          <input type="text" v-model="cfg.ytdlp_args" placeholder="e.g. --geo-bypass" />
        </div>

        <div class="field">
          <label class="field-label">ytarchive additional args</label>
          <input type="text" v-model="cfg.ytarchive_args" placeholder="e.g. --threads 3 --vp9" />
        </div>

        <div class="field">
          <label class="field-label">FFmpeg additional args</label>
          <input type="text" v-model="cfg.ffmpeg_args" placeholder="e.g. -vf scale=1280:720 -b:v 5M" />
        </div>

        <div class="field-group">
          <div class="field">
            <label class="field-label">Default Video Format</label>
            <select v-model="cfg.video_format">
              <option value="mp4">MP4 (Standard)</option>
              <option value="mkv">MKV (Matroska)</option>
              <option value="mov">MOV (QuickTime)</option>
              <option value="webm">WebM</option>
            </select>
          </div>
          <div class="field">
            <label class="field-label">Default Audio Format</label>
            <select v-model="cfg.audio_format">
              <option value="mp3">MP3 (Standard)</option>
              <option value="m4a">M4A (AAC)</option>
              <option value="wav">WAV (Uncompressed)</option>
              <option value="flac">FLAC (Lossless)</option>
              <option value="opus">Opus</option>
            </select>
          </div>
        </div>

        <div class="field" style="margin-top:14px">
          <label
            :class="['toggle-row', { checked: cfg.reencode_audio_instant }]"
            @click="cfg.reencode_audio_instant = !cfg.reencode_audio_instant"
          >
            <div class="toggle-box">
              <svg class="toggle-check" viewBox="0 0 8 8" fill="none">
                <path d="M1 4l2 2 4-4" stroke="#0a0a0b" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            Re-encode Audio on Instant Cut (Fixes WMP compatibility)
          </label>
        </div>



        <div class="field" style="margin-top:14px">
          <label
            :class="['toggle-row', { checked: cfg.show_advanced_livestream }]"
            @click="cfg.show_advanced_livestream = !cfg.show_advanced_livestream"
          >
            <div class="toggle-box">
              <svg class="toggle-check" viewBox="0 0 8 8" fill="none">
                <path d="M1 4l2 2 4-4" stroke="#0a0a0b" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            Show Advanced Livestream Options
          </label>
        </div>

        <div class="field" style="margin-top:14px">
          <label
            :class="['toggle-row', { checked: showPoolSizeSlider }]"
            @click="showPoolSizeSlider = !showPoolSizeSlider"
          >
            <div class="toggle-box">
              <svg class="toggle-check" viewBox="0 0 8 8" fill="none">
                <path d="M1 4l2 2 4-4" stroke="#0a0a0b" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            Customize Auto Proxy Pool Size
          </label>
        </div>

        <div class="field" v-if="showPoolSizeSlider" style="margin-top:14px">
          <label class="field-label">Auto Proxy Pool Size ({{ cfg.proxy_pool_size }}) <span style="color:var(--muted);font-weight:400">(Healthy proxies to maintain)</span></label>
          <input type="range" v-model.number="cfg.proxy_pool_size" min="5" max="50" step="1" />
        </div>

        <div class="field" style="margin-top:14px">
          <label
            :class="['toggle-row', { checked: cfg.high_precision_cutter }]"
            @click="cfg.high_precision_cutter = !cfg.high_precision_cutter"
          >
            <div class="toggle-box">
              <svg class="toggle-check" viewBox="0 0 8 8" fill="none">
                <path d="M1 4l2 2 4-4" stroke="#0a0a0b" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            Enable centisecond precision in Cutter
          </label>
        </div>
      </div>
    </div>

    <div class="panel">
      <div class="panel-label">Maintenance</div>
      <div class="btn-row">
        <button class="btn btn-ghost" @click="clearJobs" :disabled="clearing">
          <svg v-if="!clearing" width="13" height="13" viewBox="0 0 13 13" fill="none">
             <path d="M1 3h11M4 3V2a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v1M2 3l1 8a1 1 0 0 0 1 1h5a1 1 0 0 0 1-1l1-8" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          <span v-if="clearing" class="spinner"></span>
          Clear completed jobs
        </button>
      </div>
    </div>


    <div class="panel">
      <div class="btn-row">
        <button class="btn btn-primary" @click="save" :disabled="saving">
          <svg v-if="!saving" width="13" height="13" viewBox="0 0 13 13" fill="none">
            <path d="M2 2h7l2 2v7a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1z" stroke="currentColor" stroke-width="1.3"/>
            <path d="M4 12V8h5v4M4 2v3h4V2" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          <span v-if="saving" class="spinner"></span>
          {{ saving ? 'Saving…' : 'Save Settings' }}
        </button>
      </div>

      <div v-if="msg" :class="['msg', `msg-${msg.type}`]" style="margin-top:12px">
        {{ msg.text }}
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import axios from 'axios'

const cfg = ref({ 
  data_path: '', 
  download_path: '', 
  output_path: '', 
  cookies_path: '', 
  potoken: '',
  ytdlp_args: '',
  ytarchive_args: '',
  ffmpeg_args: '',
  video_format: 'mp4',
  audio_format: 'mp3',
  reencode_audio_instant: false,
  enable_ytdlp_potoken: false,
  show_advanced_livestream: false,
  auto_proxy_enabled: false,
  proxy_pool_size: 15,
  high_precision_cutter: false,
  proxy_enabled: false,
  proxy_type: 'socks5',
  proxy_host: '',
  proxy_port: '',
  proxy_auth_enabled: false,
  proxy_username: '',
  proxy_password: ''
})
const showAdvanced = ref(false)
const showPoolSizeSlider = ref(false)
const saving = ref(false)
const clearing = ref(false)
const msg = ref(null)

import { watch } from 'vue'
watch(showPoolSizeSlider, (val) => {
  if (!val) cfg.value.proxy_pool_size = 15
})

onMounted(async () => {
  try {
    const res = await axios.get('/api/settings')
    cfg.value = res.data
  } catch (err) {
    msg.value = { type: 'error', text: 'Failed to load settings.' }
  }
})

async function save() {
  saving.value = true
  msg.value = null
  try {
    await axios.post('/api/settings', cfg.value)
    msg.value = { type: 'success', text: 'Settings saved.' }
    // Auto-hide success message after 5 seconds
    setTimeout(() => {
      if (msg.value?.type === 'success') {
        msg.value = null
      }
    }, 5000)
  } catch (err) {
    msg.value = { type: 'error', text: err.response?.data?.detail ?? err.message }
  } finally {
    saving.value = false
  }
}

async function clearJobs() {
  clearing.value = true
  try {
    await axios.post('/api/jobs/clear')
    msg.value = { type: 'success', text: 'Completed jobs cleared.' }
  } catch (err) {
    msg.value = { type: 'error', text: 'Failed to clear jobs.' }
  } finally {
    clearing.value = false
  }
}
</script>

<style scoped>
.field-group {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
  margin-top: 14px;
}
.spinner {
  display: inline-block;
  width: 11px;
  height: 11px;
  border: 1.5px solid rgba(0,0,0,0.3);
  border-top-color: #0a0a0b;
  border-radius: 50%;
  animation: spin 0.7s linear infinite;
}
@keyframes spin { to { transform: rotate(360deg); } }

/* Hide number spinners */
input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
  -webkit-appearance: none; 
  margin: 0; 
}
input[type=number] {
  -moz-appearance: textfield;
}
</style>
